// Generated by CoffeeScript 1.6.3
(function() {
  var App, Drawer, Reader, Resizer, Writer, messages,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  messages = {
    'betahive': 'Merry Christmas Pete, Rob and Matt, I have thoroughly enjoyed working with you guys. Have a great new year!<br> Anders',
    'kaldor': 'Merry Christmas to all of you guys at Kaldor, I really hope your next year will be as successful as this one!<br> Anders',
    'agentivity': "Merry Christmas Riaan and Edd, I'm excited to see what you guys come up with in the new year!<br> Anders",
    'measured': "Merry Christmas Max and Sam, I'm amazed at how far you've come in such a short time! Looking forward to seeing some exciting projects in the new year.<br> Anders",
    'dan': "DAN! IT'S CHRISTMAS! Have a good one mate!<br> Anders",
    'tom': "Merry Christmas Tom, Jo, Milly and Dexter! Hope you have a great time together!<br> Anders",
    'condiment': 'MX C',
    'ito': 'MX ito',
    'pcs': 'MX pcs',
    'juju': 'MX juju',
    'error': 'MX Error',
    'faith': 'MX Faith',
    'solstice': 'solstice',
    'flumes': 'steve',
    'thatsbrave': 'vaughn',
    'vm': "vector meldrew",
    'kl': "To all at Kingsland Linassi, Merry Christmas and a Happy New Year!<br> Anders",
    'rtc': "To all at Real Time Content, Merry Christmas and a Happy New Year!<br> Anders",
    'crafted': "To all at Crafted, Merry Christmas and a Happy New Year!<br> Anders",
    'fesuffolk': "Thanks so much to you all for attending FESuffolk. Looking forward to seeing you next year! Merry Christmas<br> Anders",
    'iprug': "Merry Christmas IPRUG! You've made a wayward JS Dev feel very at home!<br> Anders",
    'default': "Merry Christmas <br> from Anders!",
    'alexd': "Merry Chirstmas Alex! hope you have a great one!"
  };

  Drawer = (function() {
    function Drawer(app) {
      this.app = app;
      this.draw = __bind(this.draw, this);
      this.resize = __bind(this.resize, this);
      $(this.app).on('resized', this.resize);
      this.canvas = $('canvas')[0];
      this.width = 0;
      this.height = 0;
      this.x = 0;
      this.y = 0;
      this.size = 16;
      this.ctx = this.canvas.getContext('2d');
      this.draw();
    }

    Drawer.prototype.resize = function(event, lowest) {
      this.lowest = lowest;
      this.canvas.width = this.lowest;
      this.canvas.height = this.lowest;
      $('canvas').css({
        width: this.lowest,
        height: this.lowest
      });
      $('.canvas_container').css({
        width: this.lowest,
        height: this.lowest,
        margin: "-" + (this.lowest / 2) + "px"
      });
      this.x = 0;
      this.y = 0;
      return this.limit = this.lowest;
    };

    Drawer.prototype.draw = function() {
      var random;
      random = Math.random();
      if (random < 0.5) {
        this.ctx.fillStyle = "rgba(255,255,255," + (Math.random()) + ")";
      }
      if (random > 0.5 && random < 0.8) {
        this.ctx.fillStyle = "rgba(" + (Math.ceil(Math.random() * 255)) + ",0,0,1)";
      }
      if (random > 0.8) {
        this.ctx.fillStyle = "rgba(0," + (Math.ceil(Math.random() * 255)) + ",0,1)";
      }
      if (this.y < this.limit) {
        if (Math.random() < 0.6) {
          this.ctx.fillRect(this.lowest / 2 + this.x - (this.size / 2), this.lowest / 2 + this.y - (this.size / 2), this.size, this.size);
          this.ctx.fillRect(this.lowest / 2 - this.x - (this.size / 2), this.lowest / 2 + this.y - (this.size / 2), this.size, this.size);
          this.ctx.fillRect(this.lowest / 2 + this.x - (this.size / 2), this.lowest / 2 - this.y - (this.size / 2), this.size, this.size);
          this.ctx.fillRect(this.lowest / 2 - this.x - (this.size / 2), this.lowest / 2 - this.y - (this.size / 2), this.size, this.size);
        }
        this.x += this.size;
        if (this.x > this.limit) {
          this.limit -= this.size;
          this.x = 0;
          this.y += this.size;
        }
      }
      return window.requestAnimationFrame(this.draw);
    };

    return Drawer;

  })();

  Writer = (function() {
    function Writer(app) {
      this.app = app;
      $(this.app).on('newmessage', this.update);
    }

    Writer.prototype.update = function(event, message) {
      return $('.greeting').html(message);
    };

    return Writer;

  })();

  Reader = (function() {
    function Reader(app) {
      this.app = app;
      this.updateMessage = __bind(this.updateMessage, this);
      this.updateMessage();
      $(window).on('hashchange', this.updateMessage);
    }

    Reader.prototype.updateMessage = function() {
      var key;
      key = window.location.hash.substring(1);
      if (messages[key]) {
        this.message = messages[key];
      } else {
        this.message = messages['default'];
      }
      return $(this.app).trigger('newmessage', this.message);
    };

    return Reader;

  })();

  Resizer = (function() {
    function Resizer(app) {
      this.app = app;
      this.resize = __bind(this.resize, this);
      $(window).on('resize', this.resize);
      this.counter = 3;
      this.resize();
    }

    Resizer.prototype.resize = function() {
      this.counter += 1;
      if (this.counter > 3) {
        $(this.app).trigger('resized', Math.min($(window).width(), $(window).height()));
        return this.counter = 0;
      }
    };

    return Resizer;

  })();

  App = (function() {
    function App() {
      this.drawer = new Drawer(this);
      this.writer = new Writer(this);
      this.reader = new Reader(this);
      this.resizer = new Resizer(this);
    }

    return App;

  })();

  $(function() {
    return window.app = new App;
  });

}).call(this);
